// Generated by https://quicktype.io

class Actores{
  List<Actor> listaActores = new List();

  Actores.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null) return;

    jsonList.forEach((actor){
      final nuevoActor = new Actor.fromJsonMap(actor);
      listaActores.add(nuevoActor);
    });
  }
}

class Actor {
  int castId;
  String character;
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  String profilePath;

  Actor({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  Actor.fromJsonMap( Map<String, dynamic> json){
    castId      =json['cast_id'];
    character   =json['character'];
    creditId    =json['credit_id'];
    gender      =json['gender'];
    id          =json['id'];
    name        =json['name'];
    order       =json['order'];
    profilePath =json['profile_path'];
  }

  getImage(){
    if(profilePath == null){
      return 'https://thumbs.dreamstime.com/b/no-image-available-icon-photo-camera-flat-vector-illustration-132483141.jpg';
    }else{
      return 'https://image.tmdb.org/t/p/w500/$profilePath';
    }
    
  }
}

